# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 116a473af2d35e7a7c40c438fc6d3fcde5dc97a89cd814cdae2aad2474d348eecea006ba6532126090575e8442c3d436e02260ba05f9db978c522033a963030e

test:
  secret_key_base: 61b3a4f40c9ecd7b36eeb31ebba0119109d7abebd6cf9de854e04a577d9281bb363f8d401cc04455cba76b7601875c0ee311185de9a79948c35087ede3606ce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
